export const supportedLanguages = {
  "af": "Afrikaans",
  "bs": "Bosnian",
  "ca": "Catalan",
  "sr": "Serbian",
  "da": "Danish",
  "de": "German",
  "et": "Estonian",
  "en": "English",
  "es": "Spanish (Spain)",
  "eu": "Basque",
  "fr": "French",
  "gl": "Galician",
  "hr": "Croatian",
  "id": "Indonesian",
  "it": "Italian",
  "sw": "Swahili",
  "lv": "Latvian",
  "lt": "Lithuanian",
  "hu": "Hungarian",
  "nl": "Dutch",
  "no": "Norwegian",
  "pl": "Polish",
  "pt": "Portuguese (Brazil)",
  "ro": "Romanian",
  "sl": "Slovenian",
  "sk": "Slovak",
  "fi": "Finnish",
  "sv": "Swedish",
  "tr": "Turkish",
  "vi": "Vietnamese",
  "is": "Icelandic",
  "cs": "Czech",
  "el": "Greek",
  "mn": "Mongolian",
  "ru": "Russian",
  "bg": "Bulgarian",
  "uk": "Ukrainian",
  "hy": "Armenian",
  "iw": "Hebrew",
  "ur": "Urdu",
  "ar": "Arabic",
  "fa": "Persian",
  "hi": "Hindi",
  "bn": "Bangla",
  "ml": "Malayalam",
  "th": "Thai",
  "my": "Myanmar (Burmese)",
  "ka": "Georgian",
  "ja": "Japanese",
  "zh-TW": "Chinese (Taiwan)",
  "ko": "Korean"
}
